// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using System.Runtime.InteropServices;

namespace AnitomyNg;

/// <summary>
/// P/Invoke declarations for the <c>anitomy</c> C ABI (see anitomy-c/src/lib.rs).
/// Source-generated by <see cref="LibraryImportAttribute"/>. The library name
/// <c>"anitomy"</c> resolves per-platform (anitomy.dll / libanitomy.so /
/// libanitomy.dylib) via .NET's native-library probing of the package's
/// <c>runtimes/&lt;rid&gt;/native</c> folder.
/// </summary>
internal static partial class NativeMethods
{
    private const string Lib = "anitomy";

    /// <summary>The default option mask (every category enabled).</summary>
    [LibraryImport(Lib)]
    internal static partial uint anitomy_options_default();

    /// <summary>
    /// Parses a UTF-8 filename; returns an owning result handle (or
    /// <see cref="nint.Zero"/> on failure) that must be freed with
    /// <see cref="anitomy_result_free"/>.
    /// </summary>
    [LibraryImport(Lib, StringMarshalling = StringMarshalling.Utf8)]
    internal static partial nint anitomy_parse(string input, uint options);

    [LibraryImport(Lib)]
    internal static partial nuint anitomy_result_len(nint result);

    [LibraryImport(Lib)]
    internal static partial uint anitomy_result_kind(nint result, nuint index);

    /// <summary>
    /// Borrowed pointer to the element's UTF-8 value, valid until the result is
    /// freed. Read it with <see cref="Marshal.PtrToStringUTF8(nint)"/>.
    /// </summary>
    [LibraryImport(Lib)]
    internal static partial nint anitomy_result_value(nint result, nuint index);

    [LibraryImport(Lib)]
    internal static partial nuint anitomy_result_position(nint result, nuint index);

    [LibraryImport(Lib)]
    internal static partial void anitomy_result_free(nint result);

    /// <summary>Static, non-freed C string naming an <c>ElementKind</c> discriminant.</summary>
    [LibraryImport(Lib)]
    internal static partial nint anitomy_kind_name(uint kind);

    /// <summary>Static, non-freed C string with the native library version.</summary>
    [LibraryImport(Lib)]
    internal static partial nint anitomy_version();
}
